name: gestion_de_contact_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Hive et persistance
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # URL Launcher pour WhatsApp
  url_launcher: ^6.2.2

  # Autres dépendances
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Génération Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - lib/assets/json/users.json
    - lib/assets/json/contacts.json